# Homework 01

## Setup

In [279]:
import numpy as np
import pandas as pd

data = pd.read_csv('01-intro/car_fuel_efficiency.csv')
data.sample(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
4995                  150            9.0       151.0     1996.180717   
9349                  160            NaN       167.0     3039.401343   
6582                  210            2.0       211.0     2603.789637   
629                   150            3.0       144.0     2594.349426   
1068                  190            4.0       182.0     3179.591331   

      acceleration  model_year  origin fuel_type         drivetrain  \
4995          18.0        2002  Europe    Diesel    All-wheel drive   
9349          12.4        2004     USA    Diesel  Front-wheel drive   
6582          15.9        2015    Asia    Diesel    All-wheel drive   
629           16.4        2018  Europe    Diesel    All-wheel drive   
1068          15.6        2018     USA    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
4995        1.0            19.839258  
9349       -1.0            14.592563  
6582        1.0            17.663721  
629        -1.0            16.500613  
1068        0.0            13.926363

## Answers

### Q1. Pandas version
What's the version of Pandas that you installed?

In [280]:
pd.__version__

'2.3.2'

### Q2. Records count
How many records are in the dataset?

In [281]:
# Number of rows in data set
data.shape[0]  # tuple is (rows, columns)

9704

### Q3. Fuel types
How many fuel types are presented in the dataset?

In [282]:
# List column names
data.columns

Index(['engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'model_year', 'origin', 'fuel_type', 'drivetrain',
       'num_doors', 'fuel_efficiency_mpg'],
      dtype='object')

In [283]:
# Visualise the unique 'fuel_type' values
print(data['fuel_type'].unique())

['Gasoline' 'Diesel']


In [284]:
# List the number of unique 'fuel_type' values
data['fuel_type'].nunique()

2

### Q4. Missing values
How many columns in the dataset have missing values?

In [285]:
# Visualise the number of missing values in each column
missing_values_sum = data.isnull().sum()
missing_values_sum

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [286]:
# Count of columns with missing values
print((missing_values_sum > 0).sum())

4


### Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [287]:
# Find what unique values are in the 'origin' column
print(data['origin'].unique())

['Europe' 'USA' 'Asia']


In [288]:
# Filter the data to show only records from Asia
data_asia = data[data['origin'] == 'Asia']
data_asia.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [289]:
# Print the max fuel efficiency in Asia rounded to 2 decimal places
print(data_asia['fuel_efficiency_mpg'].max().round(2))

23.76


In [290]:
# Or in one line if you really want to make your peers cry
print(data[data['origin'] == 'Asia']['fuel_efficiency_mpg'].max().round(2))

23.76


### Q6. Median value of horsepower
1. Find the median value of horsepower column in the dataset.
1. Next, calculate the most frequent value of the same horsepower column.
1. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
1. Now, calculate the median value of horsepower once again.

In [291]:
data['horsepower'].head(10)

0    159.0
1     97.0
2     78.0
3      NaN
4    140.0
5      NaN
6    127.0
7    239.0
8    174.0
9    123.0
Name: horsepower, dtype: float64

In [292]:
# 1. Find the median value of horsepower column in the dataset.
median_horsepower = data['horsepower'].median()
print(median_horsepower)

149.0


In [293]:
# 2. Next, calculate the most frequent value of the same horsepower column.
mode_horsepower = data['horsepower'].mode()[0]
print(mode_horsepower)

152.0


In [294]:
# 3. Use fillna method to fill the missing values in horsepower column
# with the most frequent value from the previous step.
missing_horsepower_count = data['horsepower'].isnull().sum()
print(f'missing_horsepower_count: {missing_horsepower_count}')

# Fill missing values with the mode (most frequent value)
filled_horsepower_series = data['horsepower'].fillna(
    mode_horsepower, inplace=False)
print(f'missing count after fillna: {filled_horsepower_series.isnull().sum()}')

missing_horsepower_count: 708
missing count after fillna: 0


In [295]:
filled_horsepower_series.head(10)

0    159.0
1     97.0
2     78.0
3    152.0
4    140.0
5    152.0
6    127.0
7    239.0
8    174.0
9    123.0
Name: horsepower, dtype: float64

In [296]:
# 4. Now, calculate the median value of horsepower once again.
new_median_horsepower = filled_horsepower_series.median()
print(new_median_horsepower)

152.0


In [297]:
print('Has it changed?')


if new_median_horsepower > median_horsepower:
    print('Yes, it increased')
elif new_median_horsepower < median_horsepower:
    print('Yes, it decreased')
else:
    print('No')

Has it changed?
Yes, it increased


### Q7. Sum of weights
1. Select all the cars from Asia
1. Select only columns vehicle_weight and model_year
1. Select the first 7 values
1. Get the underlying NumPy array. Let's call it X.
1. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
1. Invert XTX.
1. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
1. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
1. What's the sum of all the elements of the result?

In [298]:
# Select all the cars from Asia
data_asia = data[data['origin'] == 'Asia']

In [299]:
# Select only the columns 'vehicle_weight' and 'model_year'
data_asia_subset = data_asia[['vehicle_weight', 'model_year']]

In [300]:
# Select the first 7 values
data_asia_subset = data_asia_subset[:7]

In [301]:
# Get the underlying NumPy array. Let's call it X.
X = data_asia_subset.to_numpy()
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [302]:
# Compute matrix-matrix multiplication between the transpose of X and X.
# To get the transpose, use X.T. Let's call the result XTX.
X_transpose = X.T
XTX = X_transpose.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [303]:
# Invert XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [304]:
# Create an array 'y' with values [1100, 1300, 800, 900, 1000, 1100, 1200].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [305]:
# Multiply the inverse of XTX with the transpose of X, and then with y. Call the result 'w'.
w = XTX_inv.dot(X_transpose).dot(y)
w

array([0.01386421, 0.5049067 ])

In [306]:
# What's the sum of all the elements of the result?
print(w.sum().round(3))

0.519
