# 01.08 Linear algebra refresher
- Vector operations
- Multiplication
- Vector-vector multiplication
- Matrix-vector multiplication
- Matrix-matrix multiplication
- Identity matrix
- Inverse

## Setup

In [36]:
import numpy as np

## Vector operations

In [37]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])

# addition
print(f"addition: {u + v}")

# subtraction
print(f"subtraction: {u - v}")

# scalar multiplication
print(f"scalar multiplication: {2 * v}")

addition: [ 5 11 13 12]
subtraction: [-1  3 -3  0]
scalar multiplication: [ 6  8 16 12]


## Multiplication

### Vector-vector multiplication

In [38]:
# For multiplication, we need the number of elements to be the same
print(f"shape of u: {u.shape}")
print(f"shape of v: {v.shape}")

shape of u: (4,)
shape of v: (4,)


In [39]:
def vector_vector_multiplication(u, v):
    """Compute the dot product of two vectors u and v."""

    assert u.shape[0] == v.shape[0], "Shapes must be the same"

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result += u[i] * v[i]

    return result

In [40]:
# We can also use np.dot
print(f"dot product (custom function): {vector_vector_multiplication(u, v)}")
print(f"dot product (np.dot): {u.dot(v)}")

dot product (custom function): 110.0
dot product (np.dot): 110


### Matrix-vector multiplication

In [41]:
# Transposed matrix
U = np.array([[2, 4, 5, 6],
              [1, 2, 1, 2],
              [3, 1, 2, 1]])

In [42]:
def matrix_vector_multiplication(U, v):
    """Compute the product of a matrix U and a vector v."""
    assert U.shape[1] == v.shape[0], "Incompatible shapes"

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [43]:
# We can also use np.dot
print(f"dot product (custom function): {matrix_vector_multiplication(U, v)}")
print(f"dot product (np.dot): {U.dot(v)}")

dot product (custom function): [98. 31. 35.]
dot product (np.dot): [98 31 35]


### Matrix-matrix multiplication

In [44]:
V = np.array([[2, 4, 5],
              [1, 2, 1],
              [3, 1, 2],
              [1, 0, 2]])

In [ ]:
def matrix_matrix_multiplication(U, V):
    """Compute the product of two matrices U and V."""
    assert U.shape[1] == V.shape[0], "Incompatible shapes"

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))  # Initialize a matrix of zeros

    for i in range(num_cols):
        vi = V[:, i]  # Extract the i-th column of V
        # Multiply U by this column vector
        Uvi = matrix_vector_multiplication(U, vi)
        # Assign the result to the i-th column of the result matrix
        result[:, i] = Uvi

    return result

In [46]:
# We can also use np.dot
print(f"dot product (custom function): {matrix_matrix_multiplication(U, V)}")
print(f"dot product (np.dot): {U.dot(V)}")

dot product (custom function): [[29. 21. 36.]
 [ 9.  9. 13.]
 [14. 16. 22.]]
dot product (np.dot): [[29 21 36]
 [ 9  9 13]
 [14 16 22]]


### Identity Matrix

#### Description
An **Identity Matrix** is a special type of square matrix (same number of rows and columns) where all the elements on the **main diagonal** (from top-left to bottom-right) are **1s**, and all the other elements are **0s**.  

For example, a 3×3 identity matrix looks like this:

\[
I_3 =
\begin{bmatrix}
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\]

---

#### Why It’s Useful

1. **Multiplicative Neutral Element**  
   Just like multiplying a number by 1 doesn’t change its value, multiplying any matrix \(A\) by the identity matrix \(I\) (of the same size) leaves \(A\) unchanged:  
   \[
   AI = IA = A
   \]

2. **Matrix Inverses**  
   When you compute the inverse of a matrix \(A^{-1}\), the goal is to find a matrix that satisfies:  
   \[
   AA^{-1} = A^{-1}A = I
   \]  
   The identity matrix is the "target result" in this definition.

3. **Linear Transformations**  
   In linear algebra, matrices often represent transformations (like rotation, scaling, etc.). The identity matrix represents the **“do nothing”** transformation—it leaves vectors exactly as they are.

4. **Solving Systems of Equations**  
   Methods like Gaussian elimination use the identity matrix as a reference when reducing matrices to simpler forms.

---

✅ **In short**: The identity matrix is to matrices what the number **1** is to real numbers—a fundamental building block for multiplication, inverses, and understanding transformations.

In [47]:
np.eye(10)  # Identity matrix of size 10x10

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### Inverse

In [ ]:
Vs = V[:3]  # Extract the first 3 rows of V
Vs

array([[2, 4, 5],
       [1, 2, 1],
       [3, 1, 2]])

In [ ]:
Vs_inv = np.linalg.inv(Vs)  # Inverse of Vs
Vs_inv

array([[-0.2       ,  0.2       ,  0.4       ],
       [-0.06666667,  0.73333333, -0.2       ],
       [ 0.33333333, -0.66666667, -0.        ]])

In [ ]:
Vs_inv.dot(Vs)  # Should be close to the identity matrix

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 2.77555756e-17,  1.00000000e+00, -5.55111512e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [51]:
# Check if the result is close to identity within tolerance
np.allclose(Vs_inv.dot(Vs), np.eye(3))  # Returns True if close enough

True

#### Why matrix inversion only gets close enough
The reason Vs_inv.dot(Vs) only gets close to the identity matrix (rather than being exactly equal) is due to floating-point precision limitations in computer arithmetic.

**Floating-Point Precision Issues**
When computers perform calculations with real numbers, they use finite precision arithmetic (typically 64-bit floating-point). This means:

- Rounding Errors: Each arithmetic operation can introduce tiny rounding errors
- Accumulation: These small errors accumulate through the complex calculations involved in matrix inversion
- Representation Limits: Some decimal numbers cannot be represented exactly in binary floating-point format

**Why This Happens with Matrix Inversion**
Matrix inversion involves:
- Solving systems of linear equations
- Multiple division operations
- Complex elimination procedures

Each step introduces small numerical errors that compound.