# 01.07 NumPy
## Introduction to NumPy

### Setup

In [30]:
import numpy as np
np

<module 'numpy' from '/home/vscode/.local/lib/python3.11/site-packages/numpy/__init__.py'>

### Creating arrays

In [31]:
# Create a 1D array of zeros with length 10
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
# Create a 1D array of ones with length 10
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
# Create a 1D array of 2.5s with length 10
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [34]:
# Create an arbitrary array of integers
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [35]:
# Access the third element of the array
a[2]

np.int64(3)

In [36]:
# Create a 1D array with values ranging from 10 to 19
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
# Create a 1D array with 5 elements with values ranging from 0 to 1 in equal steps
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Multi-dimensional arrays

In [38]:
# Create a 2D array of zeros with 5 rows and 2 columns
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
# Create a 2D array with specific values
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
n[1, 1]  # Access the element in the second row and second column (5)

np.int64(5)

In [41]:
# Replace the element in the third row and third column with 10
n[2, 2] = 10
n

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [42]:
# Replace the first row with [1, 1, 1]
n[0] = [1, 1, 1]
n

array([[ 1,  1,  1],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [43]:
# Get the last column of the 2D array
n[:, -1]

array([ 1,  6, 10])

### Randomly generated arrays

In [44]:
np.random.rand(5, 2)  # Create a 5x2 array with random values between 0 and 1

array([[0.66459283, 0.268055  ],
       [0.63987379, 0.99262252],
       [0.61153685, 0.74475   ],
       [0.32687313, 0.19782719],
       [0.29727507, 0.67132499]])

In [45]:
# Create a 5x2 array with random values from a standard normal distribution
np.random.randn(5, 2)

array([[ 1.04809113,  1.00214653],
       [ 1.00832335,  0.55713246],
       [-0.80005381, -0.72808748],
       [ 1.37576505,  1.40872241],
       [-1.56907126, -1.4904073 ]])

In [46]:
# Create a 5x2 array with random integers between 0 and 100
np.random.randint(low=0, high=100, size=(5, 2))

array([[42, 10],
       [83, 19],
       [30, 24],
       [64, 47],
       [40,  6]])

### Element-wise operations

In [47]:
b = np.arange(5)  # Create a 1D array with values from 0 to 4
b

array([0, 1, 2, 3, 4])

In [48]:
c = b * 2  # Multiply each element by 2
c

array([0, 2, 4, 6, 8])

In [49]:
b + c

array([ 0,  3,  6,  9, 12])

### Comparison operations

In [50]:
# Create a boolean array where each element indicates if the corresponding element in b is greater than or equal to 2
b >= 2

array([False, False,  True,  True,  True])

In [51]:
# Create a boolean array where each element indicates if the corresponding element in
b > c

array([False, False, False, False, False])

In [52]:
c[c > b]  # Get elements in c that are greater than the corresponding elements in b

array([2, 4, 6, 8])

### Summarising operations

In [53]:
b

array([0, 1, 2, 3, 4])

In [54]:
b.sum()  # Sum of all elements in b

np.int64(10)

In [55]:
b.std()  # Standard deviation of elements in b

np.float64(1.4142135623730951)

In [56]:
n.std()  # Standard deviation of all elements in n (2D array)

np.float64(3.1190375216929334)

In [57]:
n.sum()  # Sum of all elements in n (2D array)

np.int64(43)